# Site wide configuration

url         : "http://localhost:4000"

profile     : true
future      : true
show_drafts : true


# Site owner

owner:
  google:
    ad-client : ""
    ad-slot   : ""
    analytics : ""
    verify    : ""
  bing:
    verify    : ""
  alexa:
    verify    : ""
  yandex:
    verify    : ""
