# Site wide configuration

source           : .tmp/src
destination      : .tmp/dist

title            : "VACSF.ORG"
description      : "A collection of articles addressing difficult and commonly misinterpreted Scriptural passages or concepts"
logo             : "site-logo.png"
teaser           : "default-teaser.png"
locale           : "en_US"
words_per_minute : 200
title_separator  : "×"

repository       : "nghin/vacsf.org.mm"
url              : "http://vacsf.org"
# url              : "https://nghin.github.io/vacsf.org.mm.deploy"


# Site owner

owner:
  name           : "Nghi Nguyen"
  email          :
  twitter        : ""
  facebook       : ""
  instagram      : ""
  tumblr         : ""
  github         : ""
  github-repo    : ""
  google:
    ad-client    : ""
    ad-slot      : ""
    analytics    : ""
    plus         : ""
    verify       : ""
  bing:
    verify       : ""
  alexa:
    verify       : ""
  yandex:
    verify       : ""
  bio            : "Faith is the substance of things hoped for."
  avatar         : "avatar.jpg" # 160x160 px image for author byline
staticman:
  allowedFields  : ['name', 'email', 'url', 'message']
  branch         : "master"
  commitMessage  : "New comment."
  filename       : comment-{@timestamp}
  format         : "yml"
  moderation     : true
  path           : "src/_data/comments/{options.slug}"
  requiredFields : ['name', 'email', 'message']
  transforms:
    email        : "md5"
  generatedFields:
    date:
      type       : "date"
      options:
        format   : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"


# Jekyll configuration

permalink        : /:categories/:title/
lsi              : true
future           : false
show_drafts      : false
markdown         : kramdown
kramdown:
  toc_levels     : 1..3
  input          : GFM
  hard_wrap      : false
  auto_ids       : true
  entity_output  : as_char
  smart_quotes   : lsquo,rsquo,ldquo,rdquo
  enable_coderay : false
highlighter      : rouge
keep_files:
  - .git
  - images
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp


# Plugins

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-tagging-related_posts
  - jekyll/tagging
  - jemoji
  - jekyll-paginate
  - jekyll-paginate-multiple


# Collections

collections:
  faqs:
    output    : true
    permalink : /:collection/:path/
    title     : FAQs
  components:
    output    : false
  colors:
    output    : false


# Front Matter Defaults

defaults:

  # Blog Articles
  - scope:
      path: _posts/articles
      type: posts
    values:
      layout: article
      category: articles
      breadcrumbs:
        - label: "Home"
          url: /

  # Articles in Vietnamese`
  - scope:
      path: _posts/articles-viet
      type: posts
    values:
      layout: article
      category: viet-studies
      breadcrumbs:
        - label: "Trang Nhà"
          url: /articles-viet/

  # Bible Studies
  - scope:
      path: _posts/bible-studies
      type: posts
    values:
      layout: article
      category: bible-studies
      breadcrumbs:
        - label: "Bible Studies"
          url: /bible-studies/

  # Bible Studies Viet
  - scope:
      path: _posts/bible-studies-Viet
      type: posts
    values:
      layout: article
      category: bible-studies-Viet
      breadcrumbs:
        - label: "Học Kinh Thánh"
          url: /bible-studies-viet/

  # Romans Study
  - scope:
      path: _posts/bible-studies/Romans
      type: posts
    values:
      layout: article
      category: Romans
      breadcrumbs:
        - label: "Romans Study"
          url: /bible-studies/Romans/

  # Ro-ma Study
  - scope:
      path: _posts/bible-studies-Viet/Romans
      type: posts
    values:
      layout: article
      category: Romans-Viet
      breadcrumbs:
        - label: "Sách Rô-ma"
          url: /bible-studies-viet/Ro-ma/

  # Galatians Study
  - scope:
      path: _posts/bible-studies/Galatians
      type: posts
    values:
      layout: article
      category: Galatians
      breadcrumbs:
        - label: "Galatians Study"
          url: /bible-studies/Galatians/

  # Galatians Study Viet
  - scope:
      path: _posts/bible-studies-Viet/Galatians
      type: posts
    values:
      layout: article
      category: Galatians-Viet
      breadcrumbs:
        - label: "Sách Ga-la-ti"
          url: /bible-studies-viet/Ga-la-ti/

  # Parables
  - scope:
      path: _posts/bible-studies/Parables
      type: posts
    values:
      layout: article
      category: parable
      breadcrumbs:
        - label: "Jesus' Parables"
          url: /bible-studies/Parables/

  # Parables Viet
  - scope:
      path: _posts/bible-studies-Viet/Parables
      type: posts
    values:
      layout: article
      category: ngu-ngon
      breadcrumbs:
        - label: "Ngụ Ngôn"
          url: /bible-studies-viet/Ngu-Ngon/

  # Baptism
  - scope:
      path: _pages/bible-studies/baptism
      type: pages
    values:
      layout: article
      category: baptism
      breadcrumbs:
        - label: "Baptism"
          url: /bible-studies/Baptism/

  # Baptism Viet
  - scope:
      path: _pages/bible-studies-Viet/baptism
      type: pages
    values:
      layout: article
      category: baptism-Viet
      breadcrumbs:
        - label: "Phép Báp-têm"
          url: /bible-studies-viet/Bap-tem/

  # Baptism Purposes
  - scope:
      path: _pages/bible-studies/baptism/purposes
      type: pages
    values:
      layout: article
      category: baptism
      breadcrumbs:
        - label: "Baptism Purposes"
          url: /baptism/purposes/

  # Baptism Purposes Viet
  - scope:
      path: _pages/bible-studies-Viet/baptism/purposes
      type: pages
    values:
      layout: article
      category: baptism-Viet
      breadcrumbs:
        - label: "Mục Đích Phép Báp-têm"
          url: /baptism-purposes-Viet/

  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: article


# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_index
  permalinks:
    tag: /tag/:name/


# Plugin: jekyll-picture-tag

picture:
  source: "images/_originals"
  output: "images"
  markup: "picture"
  presets:
    hero:
      attr:
        class: "page__hero-image"
        itemprop: "image"
      ppi: [1]
      source_1600:
        media: "(min-width: 1600px)"
        width: "1600"
      source_1024:
        media: "(min-width: 1024px)"
        width: "1024"
      source_768:
        media: "(min-width: 768px)"
        width: "768"
      source_600:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"

incremental: true

# paginate: 5
paginate_multiple:
  - paginate: 12
    paginate_path: '/page:num/'
    sub_dir: '/articles'
  - paginate: 12
    paginate_path: '/articles-viet/page:num/'
    sub_dir: '/articles-viet'
